name: InstaCurl

on: [push, workflow_dispatch]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1.1.1
      with:
        args: https://www.picuki.com/profile/the_commons_muizenberg/
