name: Curl PNG

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: add icon
      run:  curl https://www.picuki.com/profile/surfemporium > photo.png
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: photo.png
